FROM python:3.10-slim
WORKDIR /app
COPY cache-proxy/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY cache-proxy/main.py .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
