apiVersion: batch/v1
kind: Job
metadata:
  name: mzidentml-reader-job
spec:
  template:
    metadata:
      labels:
        app: mzidentml-reader
    spec:
      containers:
      - name: mzidentml-reader
        image: rappsilberlab/mzidentml-reader:2026-03-20
        imagePullPolicy: Always
        args: ["-h"]
      restartPolicy: Never
