{{- if .Values.cacheProxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-redis
  template:
    metadata:
      labels:
        app: cache-redis
    spec:
      {{- with .Values.redis.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ if .Values.redis.image.registry }}{{ .Values.redis.image.registry }}/{{ end }}{{ if .Values.redis.image.repository }}{{ .Values.redis.image.repository }}/{{ end }}{{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cache-redis-service
spec:
  selector:
    app: cache-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
{{- end -}}
