{{- if .Values.cacheProxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-proxy
  template:
    metadata:
      labels:
        app: cache-proxy
    spec:
      {{- with .Values.cacheProxy.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cache-proxy
          image: "{{ if .Values.cacheProxy.image.registry }}{{ .Values.cacheProxy.image.registry }}/{{ end }}{{ if .Values.cacheProxy.image.repository }}{{ .Values.cacheProxy.image.repository }}/{{ end }}{{ .Values.cacheProxy.image.name }}:{{ .Values.cacheProxy.image.tag }}"
          imagePullPolicy: {{ .Values.cacheProxy.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "cache-redis-service"
            - name: TARGET_URL
              value: "http://crosslinking-api-service:8080"
            - name: CACHE_SIZE
              value: "1gb"
            {{- if .Values.cacheProxy.ttl }}
            - name: CACHE_TTL
              value: {{ .Values.cacheProxy.ttl | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: cache-proxy-service
spec:
  selector:
    app: cache-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
{{- end -}}
