apiVersion: batch/v1
kind: Job
metadata:
  name: mzidentml-reader-job
spec:
  template:
    metadata:
      labels:
        app: mzidentml-reader
    spec:
      {{- with .Values.mzidentmlReader.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mzidentmlReader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mzidentmlReader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mzidentmlReader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mzidentml-reader
        image: "{{ if .Values.mzidentmlReader.image.registry }}{{ .Values.mzidentmlReader.image.registry }}/{{ end }}{{ if .Values.mzidentmlReader.image.repository }}{{ .Values.mzidentmlReader.image.repository }}/{{ end }}{{ .Values.mzidentmlReader.image.name }}:{{ .Values.mzidentmlReader.image.tag }}"
        imagePullPolicy: {{ .Values.mzidentmlReader.image.pullPolicy }}
        args: ["-h"]
      restartPolicy: Never
