apiVersion: v1
kind: ConfigMap
metadata:
  name: xiview-server-config
data:
  database.ini: |
    [postgresql]
    host=postgresql-service
    database=crosslinking
    user=xiadmin
    password={{ .Values.auth.db_password }}
    port=5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiview-server
  labels:
    app: xiview-server
spec:
  replicas: {{ .Values.xiviewServer.replicaCount }}
  selector:
    matchLabels:
      app: xiview-server
  template:
    metadata:
      labels:
        app: xiview-server
    spec:
      {{- with .Values.xiviewServer.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: application-db-config
          configMap:
            name: xiview-server-config
            items:
              - key: database.ini
                path: database.ini
      {{- with .Values.xiviewServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.xiviewServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.xiviewServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: xiview-server
          image: "{{ if .Values.xiviewServer.image.registry }}{{ .Values.xiviewServer.image.registry }}/{{ end }}{{ if .Values.xiviewServer.image.repository }}{{ .Values.xiviewServer.image.repository }}/{{ end }}{{ .Values.xiviewServer.image.name }}:{{ .Values.xiviewServer.image.tag }}"
          imagePullPolicy: {{ .Values.xiviewServer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.xiviewServer.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: application-db-config
              mountPath: /home/appuser/database.ini
              subPath: database.ini
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: xiview-server-service
spec:
  selector:
    app: xiview-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
