apiVersion: batch/v1
kind: Job
metadata:
  name: mzidentml-reader-job
spec:
  template:
    metadata:
      labels:
        app: mzidentml-reader
    spec:
      containers:
      - name: mzidentml-reader
        image: {{ .Values.image.registry }}/mzidentml-reader:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.mzidentmlReader.resources | nindent 10 }}
        args: ["-h"]
      restartPolicy: Never
