apiVersion: v1
kind: ConfigMap
metadata:
  name: xiview-server-config
data:
  database.ini: |
    [postgresql]
    host=postgresql-service
    database=crosslinking
    user=xiadmin
    password={{ .Values.auth.db_password }}
    port=5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiview-server
  labels:
    app: xiview-server
spec:
  replicas: {{ .Values.xiviewServer.replicaCount }}
  selector:
    matchLabels:
      app: xiview-server
  template:
    metadata:
      labels:
        app: xiview-server
    spec:
      volumes:
        - name: application-db-config
          configMap:
            name: xiview-server-config
            items:
              - key: database.ini
                path: database.ini
      {{- with .Values.xiviewServer.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.xiviewServer.affinity }}
affinity:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.xiviewServer.tolerations }}
tolerations:
  {{- toYaml . | nindent 2 }}
{{- end }}
containers:
        - name: xiview-server
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.xiviewServer.image.repository }}:{{ .Values.xiviewServer.image.tag }}"
          imagePullPolicy: {{ .Values.xiviewServer.image.pullPolicy }}