apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiview-frontend
  labels:
    app: xiview-frontend
spec:
  replicas: {{ .Values.xiviewFrontend.replicaCount }}
  selector:
    matchLabels:
      app: xiview-frontend
  template:
    metadata:
      labels:
        app: xiview-frontend
    spec:
      {{- with .Values.xiviewFrontend.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.xiviewFrontend.affinity }}
affinity:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.xiviewFrontend.tolerations }}
tolerations:
  {{- toYaml . | nindent 2 }}
{{- end }}
containers:
        - name: xiview-frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.xiviewFrontend.image.repository }}:{{ .Values.xiviewFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.xiviewFrontend.image.pullPolicy }}